# Generated by Django 4.2.4 on 2023-10-14 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_tasks_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
